### ISSUE TITLE
How to use this server on moomoo.io?

### ISSUE THREAD

**Issue by cklasacrcez** [Picoseconds/sanctuary#17]
Hello, I downloaded the project and started it, it runs on a local server and port 3000 but I don't understand how to run it on moomoo.io? How do I redirect websocket data from moomoo.io to my own server?

**Comment by Picoseconds** [comment]
You need a connector. I will provide one in the repo for all to use, it's a script that you need to paste in a browser extension called Tampermonkey. 

Please note that the script will only work for you on your own PC.

**Comment by Picoseconds** [comment]
Added: go to
https://github.com/Picoseconds/sanctuary/raw/master/sanctuary.user.js
with the Tampermonkey extension on and click "Install" to install the connector. Then go on http://moomoo.io.

note that https doesn't work

**Comment by cklasacrcez** [comment]
Works great. Thanks a lot.

**Comment by Picoseconds** [comment]
Happy to help!
