### ISSUE TITLE
Lags while moving the mouse around the player.

### ISSUE THREAD

**Issue by algorithmax** [Picoseconds/sanctuary#19]
When moving the mouse around a player, in the second client the animation of the first player (client) rotation is not smooth. Player sometimes shaking without any reason. And why does the arrow not show on the canvas when shooting? Why is that? Can this be improved somehow?

**Comment by algorithmax** [comment]
Okay, but what is the reason of lags on the frontend when moving the mouse
cursor around the player?

pon., 14 wrz 2020 o 16:00 Project-Magenta <notifications@github.com>
napisał(a):

**Comment by Picoseconds** [comment]
The reason is that the player updates are too fast and the client does not have time to animate.

**Comment by algorithmax** [comment]
Is there simple solution for  that?

wt., 15 wrz 2020 o 00:31 Picoseconds <notifications@github.com> napisał(a):

**Comment by cklasacrcez** [comment]
There is no .env file included in the repository with the basic ticks configuration, so either you define your own file or maybe the author will update the repository.

**Comment by Picoseconds** [comment]
@cklasacrcez we use a sane default for now

**Comment by Picoseconds** [comment]
If you assign TICK_INTERVAL in .env, you must set it to a value above 33 as it will not take effect if you don't.

**Comment by algorithmax** [comment]
k thanks.
