### ISSUE TITLE
I'm confused with something

### ISSUE THREAD

**Issue by CorruptedAI** [Picoseconds/sanctuary#21]
I'm confused on how I can open the server to other people, as I can only connect from one computer. I've used another computer at home with the same script and localhost port number, yet it seems that I am unable to connect regardless of what I change. I'm also confused on the location of which I store the environmental variable file. (so far i've only been adjusting the variables in the server.ts file)

**Comment by Picoseconds** [comment]
You cannot use localhost for connecting from another computer, you need to use your IP. If that computer is outside your LAN, you need to port forward the port the server is running on (defaults to 3000) as a TCP port. It needs to be in the root (the folder with the lib/ and src/ folders inside), and it must be called .env.

**Comment by CorruptedAI** [comment]
Sorry for the late response, I haven't looked at this in a while. I realized that I am slightly stupid in the brain and forgot to put in the IP in the script.
