### ISSUE TITLE
[BUG] Item cost doesnt show up properly.

### ISSUE THREAD

**Issue by itzTheMeow** [Picoseconds/sanctuary#29]
**Describe the bug**
When changing the items.json "food" cost to 12
![image](https://user-images.githubusercontent.com/50887230/105383134-c91e3700-5bde-11eb-808f-1bb93eea1dc1.png)
it still shows up as 10 in-game
![image](https://user-images.githubusercontent.com/50887230/105383190-d76c5300-5bde-11eb-87e6-b92d2c505633.png)
but requires 12 food to use

**To Reproduce**
1. change `"req": ["food", 10]` to `"req": ["food", 12]` in items.json
2. start server
3. log in and hover over food, it says 10

**Expected behavior**
The cost should show up as 12 food.

**Sanctuary version/commit hash**
2632321b32e1efd4c840e02ba770c1ee7f35444b

Not sure if this is a bug or just not possible due to limitations.

**Comment by Erisfiregamer1** [comment]
The moomoo client does not reflect the server value set. Its a limitation, sorry D;

**Comment by itzTheMeow** [comment]
ah ok, is there some way to get the data from the server and use something like a userscript to change it clientside?

**Comment by Erisfiregamer1** [comment]
no.

**Comment by itzTheMeow** [comment]
just did it
![image](https://user-images.githubusercontent.com/50887230/105556729-9a848700-5cd8-11eb-98de-21806fb2e745.png)
now I can edit the main script to fetch data from the server instead of hardcoding it

**Comment by itzTheMeow** [comment]
finished that thanks

**Comment by Tetous** [comment]
Wait how?

**Comment by Tetous** [comment]
Give me your discord?

**Comment by itzTheMeow** [comment]
https://themeow.ml
